steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/winged-idiom-417518/portfolio', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/winged-idiom-417518/portfolio']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'portfolio'
      - '--image'
      - 'gcr.io/winged-idiom-417518/portfolio'
      - '--platform'
      - 'managed'
      - '--region'
      - 'europe-north1'
options:
  logging: CLOUD_LOGGING_ONLY